/**
 * @TODO DYNAMIC TYPE GENERATED FROM tailwind.config.cjs
 */

export type ColorType = 'primary-lightest' | 'primary-light' | 'primary' | 'primary-dark' | 'secondary-lightest' | 'secondary-light' | 'secondary' | 'secondary-dark' | 'success-lightest' | 'success-light' | 'success' | 'success-dark' | 'danger-lightest' | 'danger-light' | 'danger' | 'danger-dark' | 'info-lightest' | 'info-light' | 'info' | 'info-dark' | 'warning-lightest' | 'warning-light' | 'warning' | 'warning-dark' | 'blue-lightest' | 'blue-light' | 'blue' | 'blue-dark' | 'indigo-lightest' | 'indigo-light' | 'indigo' | 'indigo-dark' | 'green-lightest' | 'green-light' | 'green' | 'green-dark' | 'red-lightest' | 'red-light' | 'red' | 'red-dark' | 'purple-lightest' | 'purple-light' | 'purple' | 'purple-dark' | 'yellow-lightest' | 'yellow-light' | 'yellow' | 'yellow-dark' | 'orange-lightest' | 'orange-light' | 'orange' | 'orange-dark' | 'gray-lightest' | 'gray-light' | 'gray' | 'gray-dark'

export const TextColor = {
  'primary-lightest': 'text-primary-lightest',
  'primary-light': 'text-primary-light',
  'primary': 'text-primary',
  'primary-dark': 'text-primary-dark',
  'secondary-lightest': 'text-secondary-lightest',
  'secondary-light': 'text-secondary-light',
  'secondary': 'text-secondary',
  'secondary-dark': 'text-secondary-dark',
  'success-lightest': 'text-success-lightest',
  'success-light': 'text-success-light',
  'success': 'text-success',
  'success-dark': 'text-success-dark',
  'danger-lightest': 'text-danger-lightest',
  'danger-light': 'text-danger-light',
  'danger': 'text-danger',
  'danger-dark': 'text-danger-dark',
  'info-lightest': 'text-info-lightest',
  'info-light': 'text-info-light',
  'info': 'text-info',
  'info-dark': 'text-info-dark',
  'warning-lightest': 'text-warning-lightest',
  'warning-light': 'text-warning-light',
  'warning': 'text-warning',
  'warning-dark': 'text-warning-dark',
  'blue-lightest': 'text-blue-lightest',
  'blue-light': 'text-blue-light',
  'blue': 'text-blue',
  'blue-dark': 'text-blue-dark',
  'indigo-lightest': 'text-indigo-lightest',
  'indigo-light': 'text-indigo-light',
  'indigo': 'text-indigo',
  'indigo-dark': 'text-indigo-dark',
  'green-lightest': 'text-green-lightest',
  'green-light': 'text-green-light',
  'green': 'text-green',
  'green-dark': 'text-green-dark',
  'red-lightest': 'text-red-lightest',
  'red-light': 'text-red-light',
  'red': 'text-red',
  'red-dark': 'text-red-dark',
  'purple-lightest': 'text-purple-lightest',
  'purple-light': 'text-purple-light',
  'purple': 'text-purple',
  'purple-dark': 'text-purple-dark',
  'yellow-lightest': 'text-yellow-lightest',
  'yellow-light': 'text-yellow-light',
  'yellow': 'text-yellow',
  'yellow-dark': 'text-yellow-dark',
  'orange-lightest': 'text-orange-lightest',
  'orange-light': 'text-orange-light',
  'orange': 'text-orange',
  'orange-dark': 'text-orange-dark',
  'gray-lightest': 'text-gray-lightest',
  'gray-light': 'text-gray-light',
  'gray': 'text-gray',
  'gray-dark': 'text-gray-dark',
}

export const BgColor = {
  'primary-lightest': 'bg-primary-lightest',
  'primary-light': 'bg-primary-light',
  'primary': 'bg-primary',
  'primary-dark': 'bg-primary-dark',
  'secondary-lightest': 'bg-secondary-lightest',
  'secondary-light': 'bg-secondary-light',
  'secondary': 'bg-secondary',
  'secondary-dark': 'bg-secondary-dark',
  'success-lightest': 'bg-success-lightest',
  'success-light': 'bg-success-light',
  'success': 'bg-success',
  'success-dark': 'bg-success-dark',
  'danger-lightest': 'bg-danger-lightest',
  'danger-light': 'bg-danger-light',
  'danger': 'bg-danger',
  'danger-dark': 'bg-danger-dark',
  'info-lightest': 'bg-info-lightest',
  'info-light': 'bg-info-light',
  'info': 'bg-info',
  'info-dark': 'bg-info-dark',
  'warning-lightest': 'bg-warning-lightest',
  'warning-light': 'bg-warning-light',
  'warning': 'bg-warning',
  'warning-dark': 'bg-warning-dark',
  'blue-lightest': 'bg-blue-lightest',
  'blue-light': 'bg-blue-light',
  'blue': 'bg-blue',
  'blue-dark': 'bg-blue-dark',
  'indigo-lightest': 'bg-indigo-lightest',
  'indigo-light': 'bg-indigo-light',
  'indigo': 'bg-indigo',
  'indigo-dark': 'bg-indigo-dark',
  'green-lightest': 'bg-green-lightest',
  'green-light': 'bg-green-light',
  'green': 'bg-green',
  'green-dark': 'bg-green-dark',
  'red-lightest': 'bg-red-lightest',
  'red-light': 'bg-red-light',
  'red': 'bg-red',
  'red-dark': 'bg-red-dark',
  'purple-lightest': 'bg-purple-lightest',
  'purple-light': 'bg-purple-light',
  'purple': 'bg-purple',
  'purple-dark': 'bg-purple-dark',
  'yellow-lightest': 'bg-yellow-lightest',
  'yellow-light': 'bg-yellow-light',
  'yellow': 'bg-yellow',
  'yellow-dark': 'bg-yellow-dark',
  'orange-lightest': 'bg-orange-lightest',
  'orange-light': 'bg-orange-light',
  'orange': 'bg-orange',
  'orange-dark': 'bg-orange-dark',
  'gray-lightest': 'bg-gray-lightest',
  'gray-light': 'bg-gray-light',
  'gray': 'bg-gray',
  'gray-dark': 'bg-gray-dark',
}

export default {
  BgColor,
  TextColor
}